// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: mosgortrans.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLInference_Ingest_FullMethodName       = "/mosgortrans.v1.MLInference/Ingest"
	MLInference_IngestStream_FullMethodName = "/mosgortrans.v1.MLInference/IngestStream"
	MLInference_Predict_FullMethodName      = "/mosgortrans.v1.MLInference/Predict"
	MLInference_Health_FullMethodName       = "/mosgortrans.v1.MLInference/Health"
)

// MLInferenceClient is the client API for MLInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLInferenceClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestRequest, IngestSummary], error)
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictionResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mLInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLInferenceClient(cc grpc.ClientConnInterface) MLInferenceClient {
	return &mLInferenceClient{cc}
}

func (c *mLInferenceClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, MLInference_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLInferenceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestRequest, IngestSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MLInference_ServiceDesc.Streams[0], MLInference_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestRequest, IngestSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLInference_IngestStreamClient = grpc.ClientStreamingClient[IngestRequest, IngestSummary]

func (c *mLInferenceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictionResponse)
	err := c.cc.Invoke(ctx, MLInference_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLInferenceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MLInference_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLInferenceServer is the server API for MLInference service.
// All implementations must embed UnimplementedMLInferenceServer
// for forward compatibility.
type MLInferenceServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	IngestStream(grpc.ClientStreamingServer[IngestRequest, IngestSummary]) error
	Predict(context.Context, *PredictRequest) (*PredictionResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMLInferenceServer()
}

// UnimplementedMLInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLInferenceServer struct{}

func (UnimplementedMLInferenceServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedMLInferenceServer) IngestStream(grpc.ClientStreamingServer[IngestRequest, IngestSummary]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedMLInferenceServer) Predict(context.Context, *PredictRequest) (*PredictionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedMLInferenceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMLInferenceServer) mustEmbedUnimplementedMLInferenceServer() {}
func (UnimplementedMLInferenceServer) testEmbeddedByValue()                     {}

// UnsafeMLInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLInferenceServer will
// result in compilation errors.
type UnsafeMLInferenceServer interface {
	mustEmbedUnimplementedMLInferenceServer()
}

func RegisterMLInferenceServer(s grpc.ServiceRegistrar, srv MLInferenceServer) {
	// If the following call panics, it indicates UnimplementedMLInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLInference_ServiceDesc, srv)
}

func _MLInference_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLInference_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MLInferenceServer).IngestStream(&grpc.GenericServerStream[IngestRequest, IngestSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLInference_IngestStreamServer = grpc.ClientStreamingServer[IngestRequest, IngestSummary]

func _MLInference_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLInference_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLInference_ServiceDesc is the grpc.ServiceDesc for MLInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mosgortrans.v1.MLInference",
	HandlerType: (*MLInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _MLInference_Ingest_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _MLInference_Predict_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MLInference_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _MLInference_IngestStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mosgortrans.proto",
}
