// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: mosgortrans.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UnitId          int64                  `protobuf:"varint,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	TrId            int64                  `protobuf:"varint,2,opt,name=tr_id,json=trId,proto3" json:"tr_id,omitempty"`
	EventTimeUnixMs int64                  `protobuf:"varint,3,opt,name=event_time_unix_ms,json=eventTimeUnixMs,proto3" json:"event_time_unix_ms,omitempty"`
	Lat             float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon             float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	SpeedKmh        float64                `protobuf:"fixed64,6,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	HeadingDeg      float64                `protobuf:"fixed64,7,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	LocationValid   bool                   `protobuf:"varint,8,opt,name=location_valid,json=locationValid,proto3" json:"location_valid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_mosgortrans_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEvent) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *TelemetryEvent) GetTrId() int64 {
	if x != nil {
		return x.TrId
	}
	return 0
}

func (x *TelemetryEvent) GetEventTimeUnixMs() int64 {
	if x != nil {
		return x.EventTimeUnixMs
	}
	return 0
}

func (x *TelemetryEvent) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TelemetryEvent) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *TelemetryEvent) GetSpeedKmh() float64 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *TelemetryEvent) GetHeadingDeg() float64 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *TelemetryEvent) GetLocationValid() bool {
	if x != nil {
		return x.LocationValid
	}
	return false
}

type ScheduleState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Valid                bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	CurDevS              float64                `protobuf:"fixed64,2,opt,name=cur_dev_s,json=curDevS,proto3" json:"cur_dev_s,omitempty"`
	LastKnownFactDelayS  float64                `protobuf:"fixed64,3,opt,name=last_known_fact_delay_s,json=lastKnownFactDelayS,proto3" json:"last_known_fact_delay_s,omitempty"`
	SecondsSinceLastFact float64                `protobuf:"fixed64,4,opt,name=seconds_since_last_fact,json=secondsSinceLastFact,proto3" json:"seconds_since_last_fact,omitempty"`
	LastStopId           int64                  `protobuf:"varint,5,opt,name=last_stop_id,json=lastStopId,proto3" json:"last_stop_id,omitempty"`
	LastStopOrder        int32                  `protobuf:"varint,6,opt,name=last_stop_order,json=lastStopOrder,proto3" json:"last_stop_order,omitempty"`
	MatchConfidence      float64                `protobuf:"fixed64,7,opt,name=match_confidence,json=matchConfidence,proto3" json:"match_confidence,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ScheduleState) Reset() {
	*x = ScheduleState{}
	mi := &file_mosgortrans_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleState) ProtoMessage() {}

func (x *ScheduleState) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleState.ProtoReflect.Descriptor instead.
func (*ScheduleState) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleState) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ScheduleState) GetCurDevS() float64 {
	if x != nil {
		return x.CurDevS
	}
	return 0
}

func (x *ScheduleState) GetLastKnownFactDelayS() float64 {
	if x != nil {
		return x.LastKnownFactDelayS
	}
	return 0
}

func (x *ScheduleState) GetSecondsSinceLastFact() float64 {
	if x != nil {
		return x.SecondsSinceLastFact
	}
	return 0
}

func (x *ScheduleState) GetLastStopId() int64 {
	if x != nil {
		return x.LastStopId
	}
	return 0
}

func (x *ScheduleState) GetLastStopOrder() int32 {
	if x != nil {
		return x.LastStopOrder
	}
	return 0
}

func (x *ScheduleState) GetMatchConfidence() float64 {
	if x != nil {
		return x.MatchConfidence
	}
	return 0
}

type TargetPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Valid             bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	StopId            int64                  `protobuf:"varint,2,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	TargetTimeUnixMs  int64                  `protobuf:"varint,3,opt,name=target_time_unix_ms,json=targetTimeUnixMs,proto3" json:"target_time_unix_ms,omitempty"`
	Order             int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Lon               float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat               float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	ScheduledPrevGapS float64                `protobuf:"fixed64,7,opt,name=scheduled_prev_gap_s,json=scheduledPrevGapS,proto3" json:"scheduled_prev_gap_s,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TargetPoint) Reset() {
	*x = TargetPoint{}
	mi := &file_mosgortrans_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPoint) ProtoMessage() {}

func (x *TargetPoint) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPoint.ProtoReflect.Descriptor instead.
func (*TargetPoint) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{2}
}

func (x *TargetPoint) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TargetPoint) GetStopId() int64 {
	if x != nil {
		return x.StopId
	}
	return 0
}

func (x *TargetPoint) GetTargetTimeUnixMs() int64 {
	if x != nil {
		return x.TargetTimeUnixMs
	}
	return 0
}

func (x *TargetPoint) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TargetPoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *TargetPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TargetPoint) GetScheduledPrevGapS() float64 {
	if x != nil {
		return x.ScheduledPrevGapS
	}
	return 0
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *TelemetryEvent        `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Schedule      *ScheduleState         `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_mosgortrans_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{3}
}

func (x *IngestRequest) GetTelemetry() *TelemetryEvent {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *IngestRequest) GetSchedule() *ScheduleState {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TrId          int64                  `protobuf:"varint,3,opt,name=tr_id,json=trId,proto3" json:"tr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_mosgortrans_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{4}
}

func (x *IngestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestResponse) GetTrId() int64 {
	if x != nil {
		return x.TrId
	}
	return 0
}

type IngestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int64                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Accepted      int64                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int64                  `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSummary) Reset() {
	*x = IngestSummary{}
	mi := &file_mosgortrans_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSummary) ProtoMessage() {}

func (x *IngestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSummary.ProtoReflect.Descriptor instead.
func (*IngestSummary) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{5}
}

func (x *IngestSummary) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *IngestSummary) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestSummary) GetRejected() int64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

type PredictRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrId              int64                  `protobuf:"varint,1,opt,name=tr_id,json=trId,proto3" json:"tr_id,omitempty"`
	RequestTimeUnixMs int64                  `protobuf:"varint,2,opt,name=request_time_unix_ms,json=requestTimeUnixMs,proto3" json:"request_time_unix_ms,omitempty"`
	Schedule          *ScheduleState         `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Target            *TargetPoint           `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_mosgortrans_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{6}
}

func (x *PredictRequest) GetTrId() int64 {
	if x != nil {
		return x.TrId
	}
	return 0
}

func (x *PredictRequest) GetRequestTimeUnixMs() int64 {
	if x != nil {
		return x.RequestTimeUnixMs
	}
	return 0
}

func (x *PredictRequest) GetSchedule() *ScheduleState {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *PredictRequest) GetTarget() *TargetPoint {
	if x != nil {
		return x.Target
	}
	return nil
}

type PredictionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TrId                int64                  `protobuf:"varint,2,opt,name=tr_id,json=trId,proto3" json:"tr_id,omitempty"`
	TargetStopId        int64                  `protobuf:"varint,3,opt,name=target_stop_id,json=targetStopId,proto3" json:"target_stop_id,omitempty"`
	TargetTimeUnixMs    int64                  `protobuf:"varint,4,opt,name=target_time_unix_ms,json=targetTimeUnixMs,proto3" json:"target_time_unix_ms,omitempty"`
	HorizonS            float64                `protobuf:"fixed64,5,opt,name=horizon_s,json=horizonS,proto3" json:"horizon_s,omitempty"`
	CurrentDelayS       float64                `protobuf:"fixed64,6,opt,name=current_delay_s,json=currentDelayS,proto3" json:"current_delay_s,omitempty"`
	PredictedDeltaS     float64                `protobuf:"fixed64,7,opt,name=predicted_delta_s,json=predictedDeltaS,proto3" json:"predicted_delta_s,omitempty"`
	PredictedDelayS     float64                `protobuf:"fixed64,8,opt,name=predicted_delay_s,json=predictedDelayS,proto3" json:"predicted_delay_s,omitempty"`
	LateProbability     float64                `protobuf:"fixed64,9,opt,name=late_probability,json=lateProbability,proto3" json:"late_probability,omitempty"`
	RiskLevel           string                 `protobuf:"bytes,10,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Reason              string                 `protobuf:"bytes,11,opt,name=reason,proto3" json:"reason,omitempty"`
	ReasonConfidence    float64                `protobuf:"fixed64,12,opt,name=reason_confidence,json=reasonConfidence,proto3" json:"reason_confidence,omitempty"`
	TelemetryStalenessS float64                `protobuf:"fixed64,13,opt,name=telemetry_staleness_s,json=telemetryStalenessS,proto3" json:"telemetry_staleness_s,omitempty"`
	MlLatencyMs         float64                `protobuf:"fixed64,14,opt,name=ml_latency_ms,json=mlLatencyMs,proto3" json:"ml_latency_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_mosgortrans_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{7}
}

func (x *PredictionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PredictionResponse) GetTrId() int64 {
	if x != nil {
		return x.TrId
	}
	return 0
}

func (x *PredictionResponse) GetTargetStopId() int64 {
	if x != nil {
		return x.TargetStopId
	}
	return 0
}

func (x *PredictionResponse) GetTargetTimeUnixMs() int64 {
	if x != nil {
		return x.TargetTimeUnixMs
	}
	return 0
}

func (x *PredictionResponse) GetHorizonS() float64 {
	if x != nil {
		return x.HorizonS
	}
	return 0
}

func (x *PredictionResponse) GetCurrentDelayS() float64 {
	if x != nil {
		return x.CurrentDelayS
	}
	return 0
}

func (x *PredictionResponse) GetPredictedDeltaS() float64 {
	if x != nil {
		return x.PredictedDeltaS
	}
	return 0
}

func (x *PredictionResponse) GetPredictedDelayS() float64 {
	if x != nil {
		return x.PredictedDelayS
	}
	return 0
}

func (x *PredictionResponse) GetLateProbability() float64 {
	if x != nil {
		return x.LateProbability
	}
	return 0
}

func (x *PredictionResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *PredictionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PredictionResponse) GetReasonConfidence() float64 {
	if x != nil {
		return x.ReasonConfidence
	}
	return 0
}

func (x *PredictionResponse) GetTelemetryStalenessS() float64 {
	if x != nil {
		return x.TelemetryStalenessS
	}
	return 0
}

func (x *PredictionResponse) GetMlLatencyMs() float64 {
	if x != nil {
		return x.MlLatencyMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_mosgortrans_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ModelVersion    string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	TelemetryEvents int64                  `protobuf:"varint,4,opt,name=telemetry_events,json=telemetryEvents,proto3" json:"telemetry_events,omitempty"`
	Predictions     int64                  `protobuf:"varint,5,opt,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_mosgortrans_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mosgortrans_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_mosgortrans_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetTelemetryEvents() int64 {
	if x != nil {
		return x.TelemetryEvents
	}
	return 0
}

func (x *HealthResponse) GetPredictions() int64 {
	if x != nil {
		return x.Predictions
	}
	return 0
}

var File_mosgortrans_proto protoreflect.FileDescriptor

const file_mosgortrans_proto_rawDesc = "" +
	"\n" +
	"\x11mosgortrans.proto\x12\x0emosgortrans.v1\"\xf4\x01\n" +
	"\x0eTelemetryEvent\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\x03R\x06unitId\x12\x13\n" +
	"\x05tr_id\x18\x02 \x01(\x03R\x04trId\x12+\n" +
	"\x12event_time_unix_ms\x18\x03 \x01(\x03R\x0feventTimeUnixMs\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tspeed_kmh\x18\x06 \x01(\x01R\bspeedKmh\x12\x1f\n" +
	"\vheading_deg\x18\a \x01(\x01R\n" +
	"headingDeg\x12%\n" +
	"\x0elocation_valid\x18\b \x01(\bR\rlocationValid\"\xa3\x02\n" +
	"\rScheduleState\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1a\n" +
	"\tcur_dev_s\x18\x02 \x01(\x01R\acurDevS\x124\n" +
	"\x17last_known_fact_delay_s\x18\x03 \x01(\x01R\x13lastKnownFactDelayS\x125\n" +
	"\x17seconds_since_last_fact\x18\x04 \x01(\x01R\x14secondsSinceLastFact\x12 \n" +
	"\flast_stop_id\x18\x05 \x01(\x03R\n" +
	"lastStopId\x12&\n" +
	"\x0flast_stop_order\x18\x06 \x01(\x05R\rlastStopOrder\x12)\n" +
	"\x10match_confidence\x18\a \x01(\x01R\x0fmatchConfidence\"\xd6\x01\n" +
	"\vTargetPoint\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\astop_id\x18\x02 \x01(\x03R\x06stopId\x12-\n" +
	"\x13target_time_unix_ms\x18\x03 \x01(\x03R\x10targetTimeUnixMs\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\x12/\n" +
	"\x14scheduled_prev_gap_s\x18\a \x01(\x01R\x11scheduledPrevGapS\"\x88\x01\n" +
	"\rIngestRequest\x12<\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x1e.mosgortrans.v1.TelemetryEventR\ttelemetry\x129\n" +
	"\bschedule\x18\x02 \x01(\v2\x1d.mosgortrans.v1.ScheduleStateR\bschedule\"Y\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x13\n" +
	"\x05tr_id\x18\x03 \x01(\x03R\x04trId\"c\n" +
	"\rIngestSummary\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x03R\breceived\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x03R\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\x03R\brejected\"\xc6\x01\n" +
	"\x0ePredictRequest\x12\x13\n" +
	"\x05tr_id\x18\x01 \x01(\x03R\x04trId\x12/\n" +
	"\x14request_time_unix_ms\x18\x02 \x01(\x03R\x11requestTimeUnixMs\x129\n" +
	"\bschedule\x18\x03 \x01(\v2\x1d.mosgortrans.v1.ScheduleStateR\bschedule\x123\n" +
	"\x06target\x18\x04 \x01(\v2\x1b.mosgortrans.v1.TargetPointR\x06target\"\x9a\x04\n" +
	"\x12PredictionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x13\n" +
	"\x05tr_id\x18\x02 \x01(\x03R\x04trId\x12$\n" +
	"\x0etarget_stop_id\x18\x03 \x01(\x03R\ftargetStopId\x12-\n" +
	"\x13target_time_unix_ms\x18\x04 \x01(\x03R\x10targetTimeUnixMs\x12\x1b\n" +
	"\thorizon_s\x18\x05 \x01(\x01R\bhorizonS\x12&\n" +
	"\x0fcurrent_delay_s\x18\x06 \x01(\x01R\rcurrentDelayS\x12*\n" +
	"\x11predicted_delta_s\x18\a \x01(\x01R\x0fpredictedDeltaS\x12*\n" +
	"\x11predicted_delay_s\x18\b \x01(\x01R\x0fpredictedDelayS\x12)\n" +
	"\x10late_probability\x18\t \x01(\x01R\x0flateProbability\x12\x1d\n" +
	"\n" +
	"risk_level\x18\n" +
	" \x01(\tR\triskLevel\x12\x16\n" +
	"\x06reason\x18\v \x01(\tR\x06reason\x12+\n" +
	"\x11reason_confidence\x18\f \x01(\x01R\x10reasonConfidence\x122\n" +
	"\x15telemetry_staleness_s\x18\r \x01(\x01R\x13telemetryStalenessS\x12\"\n" +
	"\rml_latency_ms\x18\x0e \x01(\x01R\vmlLatencyMs\"\x0f\n" +
	"\rHealthRequest\"\xaa\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12)\n" +
	"\x10telemetry_events\x18\x04 \x01(\x03R\x0ftelemetryEvents\x12 \n" +
	"\vpredictions\x18\x05 \x01(\x03R\vpredictions2\xbe\x02\n" +
	"\vMLInference\x12G\n" +
	"\x06Ingest\x12\x1d.mosgortrans.v1.IngestRequest\x1a\x1e.mosgortrans.v1.IngestResponse\x12N\n" +
	"\fIngestStream\x12\x1d.mosgortrans.v1.IngestRequest\x1a\x1d.mosgortrans.v1.IngestSummary(\x01\x12M\n" +
	"\aPredict\x12\x1e.mosgortrans.v1.PredictRequest\x1a\".mosgortrans.v1.PredictionResponse\x12G\n" +
	"\x06Health\x12\x1d.mosgortrans.v1.HealthRequest\x1a\x1e.mosgortrans.v1.HealthResponseB!Z\x1fbaboteek_regtrans/pkg/api/v1;v1b\x06proto3"

var (
	file_mosgortrans_proto_rawDescOnce sync.Once
	file_mosgortrans_proto_rawDescData []byte
)

func file_mosgortrans_proto_rawDescGZIP() []byte {
	file_mosgortrans_proto_rawDescOnce.Do(func() {
		file_mosgortrans_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mosgortrans_proto_rawDesc), len(file_mosgortrans_proto_rawDesc)))
	})
	return file_mosgortrans_proto_rawDescData
}

var file_mosgortrans_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mosgortrans_proto_goTypes = []any{
	(*TelemetryEvent)(nil),     // 0: mosgortrans.v1.TelemetryEvent
	(*ScheduleState)(nil),      // 1: mosgortrans.v1.ScheduleState
	(*TargetPoint)(nil),        // 2: mosgortrans.v1.TargetPoint
	(*IngestRequest)(nil),      // 3: mosgortrans.v1.IngestRequest
	(*IngestResponse)(nil),     // 4: mosgortrans.v1.IngestResponse
	(*IngestSummary)(nil),      // 5: mosgortrans.v1.IngestSummary
	(*PredictRequest)(nil),     // 6: mosgortrans.v1.PredictRequest
	(*PredictionResponse)(nil), // 7: mosgortrans.v1.PredictionResponse
	(*HealthRequest)(nil),      // 8: mosgortrans.v1.HealthRequest
	(*HealthResponse)(nil),     // 9: mosgortrans.v1.HealthResponse
}
var file_mosgortrans_proto_depIdxs = []int32{
	0, // 0: mosgortrans.v1.IngestRequest.telemetry:type_name -> mosgortrans.v1.TelemetryEvent
	1, // 1: mosgortrans.v1.IngestRequest.schedule:type_name -> mosgortrans.v1.ScheduleState
	1, // 2: mosgortrans.v1.PredictRequest.schedule:type_name -> mosgortrans.v1.ScheduleState
	2, // 3: mosgortrans.v1.PredictRequest.target:type_name -> mosgortrans.v1.TargetPoint
	3, // 4: mosgortrans.v1.MLInference.Ingest:input_type -> mosgortrans.v1.IngestRequest
	3, // 5: mosgortrans.v1.MLInference.IngestStream:input_type -> mosgortrans.v1.IngestRequest
	6, // 6: mosgortrans.v1.MLInference.Predict:input_type -> mosgortrans.v1.PredictRequest
	8, // 7: mosgortrans.v1.MLInference.Health:input_type -> mosgortrans.v1.HealthRequest
	4, // 8: mosgortrans.v1.MLInference.Ingest:output_type -> mosgortrans.v1.IngestResponse
	5, // 9: mosgortrans.v1.MLInference.IngestStream:output_type -> mosgortrans.v1.IngestSummary
	7, // 10: mosgortrans.v1.MLInference.Predict:output_type -> mosgortrans.v1.PredictionResponse
	9, // 11: mosgortrans.v1.MLInference.Health:output_type -> mosgortrans.v1.HealthResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mosgortrans_proto_init() }
func file_mosgortrans_proto_init() {
	if File_mosgortrans_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mosgortrans_proto_rawDesc), len(file_mosgortrans_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mosgortrans_proto_goTypes,
		DependencyIndexes: file_mosgortrans_proto_depIdxs,
		MessageInfos:      file_mosgortrans_proto_msgTypes,
	}.Build()
	File_mosgortrans_proto = out.File
	file_mosgortrans_proto_goTypes = nil
	file_mosgortrans_proto_depIdxs = nil
}
