// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/mosgortrans.proto

package mosgortransv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MLInference_Ingest_FullMethodName       = "/mosgortrans.v1.MLInference/Ingest"
	MLInference_IngestStream_FullMethodName = "/mosgortrans.v1.MLInference/IngestStream"
	MLInference_Predict_FullMethodName      = "/mosgortrans.v1.MLInference/Predict"
	MLInference_Health_FullMethodName       = "/mosgortrans.v1.MLInference/Health"
)

// MLInferenceClient is the client API for MLInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLInferenceClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (MLInference_IngestStreamClient, error)
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictionResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mLInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLInferenceClient(cc grpc.ClientConnInterface) MLInferenceClient {
	return &mLInferenceClient{cc}
}

func (c *mLInferenceClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, MLInference_Ingest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLInferenceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (MLInference_IngestStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MLInference_ServiceDesc.Streams[0], MLInference_IngestStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mLInferenceIngestStreamClient{stream}
	return x, nil
}

type MLInference_IngestStreamClient interface {
	Send(*IngestRequest) error
	CloseAndRecv() (*IngestSummary, error)
	grpc.ClientStream
}

type mLInferenceIngestStreamClient struct {
	grpc.ClientStream
}

func (x *mLInferenceIngestStreamClient) Send(m *IngestRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mLInferenceIngestStreamClient) CloseAndRecv() (*IngestSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IngestSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mLInferenceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictionResponse, error) {
	out := new(PredictionResponse)
	err := c.cc.Invoke(ctx, MLInference_Predict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLInferenceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MLInference_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLInferenceServer is the server API for MLInference service.
// All implementations must embed UnimplementedMLInferenceServer
// for forward compatibility
type MLInferenceServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	IngestStream(MLInference_IngestStreamServer) error
	Predict(context.Context, *PredictRequest) (*PredictionResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMLInferenceServer()
}

// UnimplementedMLInferenceServer must be embedded to have forward compatible implementations.
type UnimplementedMLInferenceServer struct {
}

func (UnimplementedMLInferenceServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedMLInferenceServer) IngestStream(MLInference_IngestStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedMLInferenceServer) Predict(context.Context, *PredictRequest) (*PredictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedMLInferenceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMLInferenceServer) mustEmbedUnimplementedMLInferenceServer() {}

// UnsafeMLInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLInferenceServer will
// result in compilation errors.
type UnsafeMLInferenceServer interface {
	mustEmbedUnimplementedMLInferenceServer()
}

func RegisterMLInferenceServer(s grpc.ServiceRegistrar, srv MLInferenceServer) {
	s.RegisterService(&MLInference_ServiceDesc, srv)
}

func _MLInference_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLInference_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MLInferenceServer).IngestStream(&mLInferenceIngestStreamServer{stream})
}

type MLInference_IngestStreamServer interface {
	SendAndClose(*IngestSummary) error
	Recv() (*IngestRequest, error)
	grpc.ServerStream
}

type mLInferenceIngestStreamServer struct {
	grpc.ServerStream
}

func (x *mLInferenceIngestStreamServer) SendAndClose(m *IngestSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mLInferenceIngestStreamServer) Recv() (*IngestRequest, error) {
	m := new(IngestRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MLInference_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLInference_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLInference_ServiceDesc is the grpc.ServiceDesc for MLInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mosgortrans.v1.MLInference",
	HandlerType: (*MLInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _MLInference_Ingest_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _MLInference_Predict_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MLInference_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _MLInference_IngestStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mosgortrans.proto",
}
